version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.4
  win: circleci/windows@2.2.0

jobs:
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-windows-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          key: dependency-cache-windows-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:  npm t
      - run:
          command: bash scripts/package.sh
          shell: bash.exe

  build-macos:
    macos:
      xcode: 10.1.0
    steps:
      - run: sudo npm install -g n
      - run: sudo n 12
      - checkout
      - restore_cache:
          key: dependency-cache-macos-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          key: dependency-cache-macos-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm t
      - run: scripts/package.sh

  build-linux:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-linux-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          key: dependency-cache-linux-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm run test:all:coverage
      - run: npm run e2e:uws
       # Package time
      - run: sudo apt-get install ruby ruby-dev rubygems build-essential rpm
      - run: sudo gem install --no-document fpm || echo "fpm install failed"
      - run: scripts/package.sh

workflows:
    master:
      jobs:
        - build-linux
        - build-windows:
            requires:
              - build-linux
        - build-macos:
            requires:
              - build-linux